# Generated by Django 2.2.12 on 2021-06-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0002_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
