# Generated by Django 3.2.3 on 2021-06-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0003_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
